### ISSUE TITLE
Needs a better name for discoverability

### ISSUE THREAD

**Issue by ritz078** [tkh44/babel-plugin-sitrep#7]
Suggestions

- logger
- linelogger
- logs

Feel free to add more.

**Comment by djfarly** [comment]
Maybe as a configuration option?

**Comment by ritz078** [comment]
Of course, you can configure the name that you want to use in your code but the plugin still needs to have a name that is different than `babel-plugin-siterep`

**Comment by djfarly** [comment]
True :)

**Comment by peterpme** [comment]
Hey @ritz078 and @djfarly!

Feel free to open up a PR 😄

**Comment by tkh44** [comment]
@ritz078 I like the name. The tags on the package.json are for discoverability more so than the name. 

How many people before me have had this idea and implemented it? Handful? People are not searching for it because it is a novel idea. What I mean by that is that when was the last time you googled "Babel plugin that logs for me"? 😄

**Comment by ritz078** [comment]
You are definitely right in that sense. 👍
